FROM registry.access.redhat.com/ubi8/openjdk-21

ENV LANGUAGE='en_GB:en'

COPY target/ /deployments/

EXPOSE 8080
USER 1001
ENV JAVA_OPTS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"

ENTRYPOINT [ "/opt/jboss/container/java/run/run-java.sh" ]
